### ISSUE TITLE
Support Dark Mode

### ISSUE THREAD

**Issue by yutailang0119** [a-know/Pixela#10]
Hi @a-know 

Please support Dark Mode.

For [graph detail HTML](https://docs.pixe.la/entry/get-graph-html), use `color-scheme` .
In the case of [SVG](https://docs.pixe.la/entry/get-svg), I think it is better to judge it with `color` query.

**Comment by a-know** [comment]
Added support for dark mode!! Thank you for feedback!!
https://github.com/a-know/Pixela/releases/tag/v1.16.0
