### ISSUE TITLE
ホームページのapi documentへのリンクが間違っています

### ISSUE THREAD

**Issue by miyamonz** [a-know/Pixela#11]
`ここで紹介したAPIは、全体のほんの一部です。シンプルでかつ簡単なAPIで、Pixela を活用してみましょう！`
の下のボタンのリンクがgithubのこのリポジトリへのリンクになってしまっています
[![Image from Gyazo](https://i.gyazo.com/b1894f3a1c1e156a3c935a4b657292ba.gif)](https://gyazo.com/b1894f3a1c1e156a3c935a4b657292ba)

しばらくこのリポジトリを巡回して「APIどこ？」ってなってしまったので修正していただけると他の人が迷子にならないのではと思います

**Comment by a-know** [comment]
ありがとうございます！全然気が付きませんでした...！

早速修正いたしました！ご報告、感謝します！！

---

Thank you so much! I didn't notice that at all...!

I fixed it right away! Thank you so much for the report!
