### ISSUE TITLE
API to get graph pixels list returns response without CORS headers

### ISSUE THREAD

**Issue by ryosms** [a-know/Pixela#12]
[Get graph pixels list](https://docs.pixe.la/entry/get-graph-pixels)

Because of returnning response without CORS headers,  my request is failed using axios.
I guess, it doesn't implement the `OPTIONS` method.

The error message below.

```
Access to XMLHttpRequest at 'https://pixe.la/v1/users/ryosms/graphs/<awesome-graph-id>/pixels' from origin 'https://my-awesome-app.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by a-know** [comment]
@ryosms 
Thanks for the report! I will check!

**Comment by a-know** [comment]
@ryosms 
I checked the code, so as you pointed out, the routing of the `OPTIONS` method was missing.
I immediately addressed this and also deployed it. Can you check it to see if it's OK? 😄

**Comment by ryosms** [comment]
@a-know 

I checked it!
It looks to be working well!

Thank you quickly fix 👍

**Comment by a-know** [comment]
Sounds like it's working as expected, I'm glad it's working for you too!
Thank you for reporting back to me this time! 😄
