### ISSUE TITLE
Request to change blog links on wiki

### ISSUE THREAD

**Issue by jagijagijag1** [a-know/Pixela#14]
Due to the end of the blog service Qrunch, I migrated my articles to own GitHub Pages.
I would appreciate it if you could modify the links to my articles on the wiki [Useful case examples](https://github.com/a-know/Pixela/wiki/Useful-case-examples) page.

My articles are the follwoing:
- リングフィットアドベンチャーの運動ログをサーバーレスでPixelaに記録する
  - OLD: <https://jagijagijag1.qrunch.io/entries/4sikGaH0wmD8vabA>
  - NEW: <https://jagijagijag1.github.io/blog/posts/2020_01_26/>
- "あとで読む"をPixelaで可視化
  - OLD: <https://jagijagijag1.qrunch.io/entries/1wk9NVnjfsCfaoZS>
  - NEW: <https://jagijagijag1.github.io/blog/posts/2018_12_02/>
  
Thank you for providing such a cool app!

**Comment by a-know** [comment]
Thank you for telling me that you migrated the article!
I immediately updated it with the following revision.

https://github.com/a-know/Pixela/wiki/Useful-case-examples/2d68bb52f4812782622093a8d58b2b17ff27293d

Please check it. And if there is no problem, please close this issue.

Thank you for always using Pixela! :)

**Comment by jagijagijag1** [comment]
Nothing wrong, thank you for your prompt response!
