### ISSUE TITLE
GET - /v1/users/<username>/graphs/<graphID>/graph-def のExampleが間違っている

### ISSUE THREAD

**Issue by sue445** [a-know/Pixela#16]
https://docs.pixe.la/entry/get-a-graph-def のExampleに

```
$ curl -X GET https://pixe.la/v1/users/a-know/graphs/test-graph -H 'X-USER-TOKEN:thisissecret'
```

とありますが、正しくは

```
$ curl -X GET https://pixe.la/v1/users/a-know/graphs/test-graph/graph-def -H 'X-USER-TOKEN:thisissecret'
```

だと思われます

**Comment by a-know** [comment]
@sue445 
ご指摘ありがとうございます！ご指摘のとおり、間違っておりました！
修正しました、ご確認くださいっ！
https://docs.pixe.la/entry/get-a-graph-def

---

Oops! Thank you for your comments! ​As you pointed out, it was wrong!
I have corrected it, please check it!
https://docs.pixe.la/entry/get-a-graph-def

**Comment by sue445** [comment]
🙆‍♀️
