### ISSUE TITLE
Unescaped '<' not allowed in attributes values at GET - /v1/users/<username>/graphs/<graphID>

### ISSUE THREAD

**Issue by sue445** [a-know/Pixela#18]
[GET - /v1/users/<username>/graphs/<graphID>](https://docs.pixe.la/entry/get-svg) で `Unescaped '<' not allowed in attributes values` というエラーになります

# Expected
https://pixe.la/v1/users/sue445/graphs/tweets でSVGが返る

# Actual
ステータスコードは200なのですが実際にはSVGは返ってこないで下記のようなエラーになります
![image](https://user-images.githubusercontent.com/608755/118396789-1c376080-b68c-11eb-9bff-fc3336f79653.png)

https://pixe.la/@sue445 を見る限り、他のグラフも死んでいるように見えます

![image](https://user-images.githubusercontent.com/608755/118396888-8cde7d00-b68c-11eb-8583-07c0535c68dd.png)

**Comment by a-know** [comment]
@sue445 
不具合のご報告、ありがとうございます！問題の箇所が特定できたため、さきほど修正をおこないました！ご確認いただけますとうれしいです！いつもありがとうございます！！

Thank you for reporting the bug! I've identified the problem and have just fixed it. I hope you'll check it out. Thanks!

**Comment by sue445** [comment]
@a-know ありがとうございます。修正されてるのを確認しました！
