### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by anony-byte** [a-know/Pixela#26]
Hai,

Can I know how to format the time zone in post graph payload. It is always showing me "Invalid Time Zonw"

**Comment by a-know** [comment]
@anony-byte 
Thank you for your question and I'm sorry that my undocumentation about it.

It is [TZ database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by anony-byte** [comment]
But when I am using IST as my time unit, it is saying invalid again.
Anyway, Asia/Kolkata worked for me

**Comment by a-know** [comment]
Yeah `IST` is not TZ database name, it is `Time zone abbreviation` .

If your problem was solved, please close this issue. Thanks!
