### ISSUE TITLE
Pateron Here - Posting Data for more than multiple days at 1 time

### ISSUE THREAD

**Issue by boringpapa** [a-know/Pixela#30]
Using the current method I can post the data for 1 single date

$ curl -X POST https://pixe.la/v1/users/a-know/graphs/test-graph -H 'X-USER-TOKEN:thisissecret' -d '{"date":"20180915","quantity":"5","optionalData":"{\"key\":\"value\"}"}'

How do I modify the above to enter data for mulitple dates say
date:20180914 , qty 3
date:20180913 , qty 5
date:20180912 , qty 6

**Comment by a-know** [comment]
Hi @pakiyabhai ,

Unfortunately, there is no way to post multiple pixel data simultaneously.
Please repeat a command to post single-pixel data.

If my answer solves your question, please close this issue. Thanks

**Comment by boringpapa** [comment]
Thank You !

**Comment by a-know** [comment]
@pakiyabhai 
Thank you for your confirmation.

BTW, we also prepared Patreon tier for getting our technical support: https://www.patreon.com/bePatron?u=19694440
If you need more our technical support, please consider upgrade your Patreon tier. Thanks!

**Comment by boringpapa** [comment]
Sure Thanks a-know. We are trying to see if we can integrate pixela with some of the low code software we use, if we can defintely , we will defintely look at higher patreon tier.

 One last question is how many such 1 day per request can we post , I've data set of say 500+ days , so those are fine to make ?

**Comment by a-know** [comment]
@pakiyabhai 
Cool!! I'm really looking forward to your product! 😍 

> One last question is how many such 1 day per request can we post , I've data set of say 500+ days , so those are fine to make ?

Regarding rate limit, we're very sorry but its specifications are not disclosed to the public.
If an error occurs, please retry with proper error handling.


In addition, let me ask you a question.
If you could hide the "Pixela" logo in the graph if you tier it further than it is now, would that be worth paying more for you? Just a question.

**Comment by boringpapa** [comment]
Rather hiding Pixela logo , it would be worth paying for extra premium features

**Comment by a-know** [comment]
@pakiyabhai 
I see, interesting.
Are there any features what you want in addition to multiple pixels post API?

**Comment by a-know** [comment]
@pakiyabhai 
Sorry again and again, but one more thing... this is friendly reminder:

If you are going to pay out a Pixela user account for each end user of the service you are developing, you will need to obtain agreement to Pixela's Terms of Use from each end user.

> If you let a person register User of Pixela by integrating Pixela’s API into your service, for example, please make sure that the person agrees to Pixela’s terms of Service and confirms that he or she is not a minor.
>
> https://help.pixe.la/en/about-user
