### ISSUE TITLE
Cant create graph

### ISSUE THREAD

**Issue by zyzz15620** [a-know/Pixela#33]
**My code return this** 
{"graphs":[]}

**instead of this**
{"message":"Success.","isSuccess":true}

**I tried to delete, created it again and still not working**

**Below is my code (python)**
![Screenshot 2023-12-04 212358](https://github.com/a-know/Pixela/assets/113292376/6f76856d-7a0a-453d-9eb6-703d42d70f0f)

**Comment by a-know** [comment]
@zyzz15620 plz show me your full codes. Thanks

**Comment by zyzz15620** [comment]
import requests
from datetime import datetime
TOKEN = "Ducbeo@156Ducbeo@156Ducbeo@156"
USERNAME = "total650"
GRAPH_ID = "meow"
PIXELA_ENDPOINT = "https://pixe.la/v1/users/"


## CREATING USER
# user_params = {
#     "token": TOKEN,
#     "username": USERNAME,
#     "agreeTermsOfService": "yes",
#     "notMinor": "yes"
# }
# response = requests.post(url=pixela_endpoint, json=user_params)
# print(response.text)


## CREATING GRAPH
graph_endpoint = f"{PIXELA_ENDPOINT}/{USERNAME}/graphs"
graph_config = {
    "id": GRAPH_ID,
    "name": "Coding",
    "unit": "Min",
    "type": "int",
    "color": "ajisai"
}
headers = {
    "X-USER-TOKEN": TOKEN
}
response = requests.post(url=graph_endpoint, json=graph_config, headers=headers)
print(response.text)

**Comment by zyzz15620** [comment]
![image](https://github.com/a-know/Pixela/assets/113292376/291ffd6a-0d97-4dc6-ba68-b0c4ba46bf1b)

**Comment by zyzz15620** [comment]
@a-know here is my code
![image](https://github.com/a-know/Pixela/assets/113292376/b87a7046-b951-4169-a93a-5a4a05797d88)

**Comment by a-know** [comment]
@zyzz15620 
I see.

`PIXELA_ENDPOINT = "https://pixe.la/v1/users/"` is wrong.
`PIXELA_ENDPOINT = "https://pixe.la/v1/users"` is correct. `/` is duplicated.

**Comment by a-know** [comment]
@zyzz15620 
We have a program to assist in resolving coding issues like this one. Please consider signing up for the program if you need our help in the future.

https://www.patreon.com/join/pixe_la

Happy coding!
