### ISSUE TITLE
GET - /v1/users/<username>/graphs/<graphID>/pixels – doesn't work with JSON

### ISSUE THREAD

**Issue by Alex-V69** [a-know/Pixela#36]
I was having a hard time figuring out why I got '400' constantly. Apparently this endpoint doesn't support JSON because when I send parameters in the query string everything works, but when I send them as JSON data it doesn't.

**Comment by a-know** [comment]
@Alex-V69 
Thank you for approaching. Yes. It is showed in our API document as examples: https://docs.pixe.la/entry/get-graph-pixels

**Comment by Alex-V69** [comment]
Well, I just thought that since it wasn't mentioned in the documentation anywhere (that the only correct response form is a query string in a URL) it may be a bug – after all, 'Update a pixel', for instance, accepts parameters in JSON format.

**Comment by a-know** [comment]
@Alex-V69 
Normally, the GET endpoint of the REST API cannot specify a request body, but specifies parameters with query string. The "Update a pixel" API is a PUT endpoint, so a JSON structure can be specified as the request body.

**Comment by Alex-V69** [comment]
I see. Thank you for explaining that.

**Comment by Alex-V69** [comment]
I see. Thank you for explaining that.
