### ISSUE TITLE
Response has no CORS headers in case of error response

### ISSUE THREAD

**Issue by ryosms** [a-know/Pixela#8]
EX: [Get a Pixel](https://docs.pixe.la/#/get-pixel) API

If Pixel is registerd, API return 200 status with CORS headers.
But in case of error,  API return `without` CORS headers.
Add CORS headers even in case of error response, please.

thanks.

**Comment by a-know** [comment]
Done!!
Thank you for feedback! Let me know if you have any questions or concerns.
